version: '3.4'

services:
  ddc:
    image: luniki/deep_doc_class
    volumes:
      - './files:/files'
      - './results:/results'
    command: ["./classify.run", "-fp", "../files", "-meta", "../files/metadata.csv"]
